version: '3.10'


volumes:
  dbdata:


networks:
  chat:
    driver: bridge


services:
#  redis:
#    image: redis:latest
#    container_name: redis_server
#    ports:
#      - "6379:6379"
#    volumes:
#      - redis:/data
#    networks:
#      - chat
  api:
    build:
      context: .
    ports:
      - 8000:8000
    volumes:
      - .:/home/chat/socket_chat
    env_file: .env
    container_name: socket_chat_django
    depends_on:
      - db
    links:
      - db
    networks:
      - chat
  db:
    image: postgres:alpine
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    container_name: chat-socket-db
    ports:
      - 5432:5432
    volumes:
      - dbdata:/var/lib/postgresql
    networks:
      - chat
