# Generated by Django 4.2.1 on 2023-06-24 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='description',
            field=models.CharField(editable=False, help_text='A description of the event that occurred', max_length=300),
        ),
        migrations.AlterField(
            model_name='event',
            name='type',
            field=models.CharField(choices=[('Join', 'join'), ('Left', 'left')], max_length=50),
        ),
    ]
